"""Add complaint_id to transaction model

Revision ID: c434ee60ccfa
Revises: 48abf8dbab7b
Create Date: 2023-04-02 16:38:12.687664

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c434ee60ccfa'
down_revision = '48abf8dbab7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.alter_column('complaint_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.alter_column('complaint_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
